"""empty message

Revision ID: 147d13744290
Revises: f3b5ccd12e47
Create Date: 2020-05-28 20:14:38.364481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147d13744290'
down_revision = 'f3b5ccd12e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedure_approvals', sa.Column('procedure_approval_flowname', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procedure_approvals', 'procedure_approval_flowname')
    # ### end Alembic commands ###
