"""empty message

Revision ID: 177f21185099
Revises: 8b97d15a427e
Create Date: 2020-06-04 20:50:34.694112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '177f21185099'
down_revision = '8b97d15a427e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedure_approvals', sa.Column('procedure_approval_flowmodal', sa.String(length=25), nullable=True))
    op.drop_column('procedure_approvals', 'procedure_approval_user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedure_approvals', sa.Column('procedure_approval_user_name', mysql.VARCHAR(length=25), nullable=True))
    op.drop_column('procedure_approvals', 'procedure_approval_flowmodal')
    # ### end Alembic commands ###
