"""empty message

Revision ID: 2131041bb3ed
Revises: 6c04b7b9fd2b
Create Date: 2020-07-18 15:39:32.462637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2131041bb3ed'
down_revision = '6c04b7b9fd2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedure_states', sa.Column('procedure_state_approval_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procedure_states', 'procedure_state_approval_datetime')
    # ### end Alembic commands ###
