"""empty message

Revision ID: 292864d04ac3
Revises: a173b060cd0a
Create Date: 2020-06-20 21:09:07.350705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '292864d04ac3'
down_revision = 'a173b060cd0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_procedure_infos', 'procedure_no')
    op.drop_column('car_procedure_infos', 'rejectreason')
    op.add_column('package_procedure_infos', sa.Column('state', sa.Integer(), nullable=True))
    op.drop_constraint('procedure_lists_ibfk_1', 'procedure_lists', type_='foreignkey')
    op.drop_column('procedure_lists', 'procedure_list_department')
    op.drop_column('procedure_lists', 'procedure_list_departmentid')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('procedure_lists', sa.Column('procedure_list_departmentid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('procedure_lists', sa.Column('procedure_list_department', mysql.VARCHAR(length=20), nullable=True))
    op.create_foreign_key('procedure_lists_ibfk_1', 'procedure_lists', 'company_departments', ['procedure_list_departmentid'], ['id'])
    op.drop_column('package_procedure_infos', 'state')
    op.add_column('car_procedure_infos', sa.Column('rejectreason', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('car_procedure_infos', sa.Column('procedure_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
