"""empty message

Revision ID: 30c7c6ca2836
Revises: f584d76ac209
Create Date: 2020-06-20 21:35:53.673140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30c7c6ca2836'
down_revision = 'f584d76ac209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_procedure_infos', sa.Column('approval_user_id', sa.Integer(), nullable=True))
    op.add_column('package_procedure_infos', sa.Column('collect_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'package_procedure_infos', 'users', ['collect_user_id'], ['id'])
    op.create_foreign_key(None, 'package_procedure_infos', 'users', ['approval_user_id'], ['id'])
    op.drop_column('package_procedure_infos', 'approval_person')
    op.drop_column('package_procedure_infos', 'collect_person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_procedure_infos', sa.Column('collect_person', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('package_procedure_infos', sa.Column('approval_person', mysql.VARCHAR(length=15), nullable=True))
    op.drop_constraint(None, 'package_procedure_infos', type_='foreignkey')
    op.drop_constraint(None, 'package_procedure_infos', type_='foreignkey')
    op.drop_column('package_procedure_infos', 'collect_user_id')
    op.drop_column('package_procedure_infos', 'approval_user_id')
    # ### end Alembic commands ###
