"""empty message

Revision ID: 398c6ff662ac
Revises: 147d13744290
Create Date: 2020-05-28 21:06:49.475606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '398c6ff662ac'
down_revision = '147d13744290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_procedure_infos_ibfk_2', 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint('car_procedure_infos_ibfk_3', 'car_procedure_infos', type_='foreignkey')
    op.drop_column('car_procedure_infos', 'confirmer')
    op.drop_column('car_procedure_infos', 'first_approval')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_procedure_infos', sa.Column('first_approval', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('car_procedure_infos', sa.Column('confirmer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('car_procedure_infos_ibfk_3', 'car_procedure_infos', 'users', ['first_approval'], ['id'])
    op.create_foreign_key('car_procedure_infos_ibfk_2', 'car_procedure_infos', 'users', ['confirmer'], ['id'])
    # ### end Alembic commands ###
