"""empty message

Revision ID: 57c037f27091
Revises: f20c162ee0af
Create Date: 2020-05-12 17:34:01.818925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57c037f27091'
down_revision = 'f20c162ee0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_procedure_infos', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_procedure_infos', sa.Column('number', mysql.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
