"""empty message

Revision ID: 68f9e0d42c42
Revises: e61a44c4c310
Create Date: 2020-04-27 17:47:22.188923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f9e0d42c42'
down_revision = 'e61a44c4c310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_procedure_infos', sa.Column('driver', sa.String(length=10), nullable=True))
    op.add_column('car_procedure_infos', sa.Column('outmiles', sa.Integer(), nullable=True))
    op.add_column('car_procedure_infos', sa.Column('rejectreason', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_procedure_infos', 'rejectreason')
    op.drop_column('car_procedure_infos', 'outmiles')
    op.drop_column('car_procedure_infos', 'driver')
    # ### end Alembic commands ###
