"""empty message

Revision ID: 6bd32fa5cc8f
Revises: 57c037f27091
Create Date: 2020-05-12 17:34:39.623263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd32fa5cc8f'
down_revision = '57c037f27091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_procedure_infos', sa.Column('number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_procedure_infos', 'number')
    # ### end Alembic commands ###
