"""empty message

Revision ID: 6c04b7b9fd2b
Revises: 99b8eb043f38
Create Date: 2020-07-18 15:38:05.485510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c04b7b9fd2b'
down_revision = '99b8eb043f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procedure_states', 'procedure_state_approval_datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedure_states', sa.Column('procedure_state_approval_datetime', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
