"""empty message

Revision ID: 86688bb4055d
Revises: 9efe8d327e5e
Create Date: 2020-06-24 21:55:46.288961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86688bb4055d'
down_revision = '9efe8d327e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedure_lists', sa.Column('procedure_list_address', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procedure_lists', 'procedure_list_address')
    # ### end Alembic commands ###
