"""empty message

Revision ID: 877e7fe6fbbe
Revises: d23cc053398e
Create Date: 2020-04-06 10:49:46.190850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '877e7fe6fbbe'
down_revision = 'd23cc053398e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_procedure_infos', sa.Column('approval_department', sa.String(length=15), nullable=True))
    op.add_column('package_procedure_infos', sa.Column('approval_person', sa.String(length=15), nullable=True))
    op.add_column('package_procedure_infos', sa.Column('collect_department', sa.String(length=15), nullable=True))
    op.add_column('package_procedure_infos', sa.Column('collect_person', sa.String(length=15), nullable=True))
    op.drop_column('package_procedure_infos', 'department')
    op.drop_column('package_procedure_infos', 'person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_procedure_infos', sa.Column('person', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('package_procedure_infos', sa.Column('department', mysql.VARCHAR(length=15), nullable=True))
    op.drop_column('package_procedure_infos', 'collect_person')
    op.drop_column('package_procedure_infos', 'collect_department')
    op.drop_column('package_procedure_infos', 'approval_person')
    op.drop_column('package_procedure_infos', 'approval_department')
    # ### end Alembic commands ###
