"""empty message

Revision ID: 8d9c7ff79eba
Revises: d074a21d483d
Create Date: 2020-07-14 21:35:27.846250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d9c7ff79eba'
down_revision = 'd074a21d483d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('size', sa.String(length=15), nullable=True))
    op.add_column('orders', sa.Column('house_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['date', 'time', 'house_id', 'company'])
    op.create_foreign_key(None, 'orders', 'houses', ['house_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'house')
    op.drop_column('orders', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('orders', sa.Column('house', mysql.VARCHAR(length=15), nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'user_id')
    op.drop_column('orders', 'house_id')
    op.drop_column('houses', 'size')
    # ### end Alembic commands ###
