"""empty message

Revision ID: 99b8eb043f38
Revises: 8d9c7ff79eba
Create Date: 2020-07-18 15:16:05.125114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b8eb043f38'
down_revision = '8d9c7ff79eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_procedure_infos_ibfk_2', 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint('car_procedure_infos_ibfk_1', 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint('car_procedure_infos_ibfk_3', 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint('car_procedure_infos_ibfk_4', 'car_procedure_infos', type_='foreignkey')
    op.create_foreign_key(None, 'car_procedure_infos', 'procedure_lists', ['procedure_list_id'], ['procedure_list_id'])
    op.create_foreign_key(None, 'car_procedure_infos', 'car_lists', ['car_id'], ['id'])
    op.create_foreign_key(None, 'car_procedure_infos', 'company_departments', ['departmentid'], ['id'])
    op.create_foreign_key(None, 'car_procedure_infos', 'users', ['user_id'], ['id'])
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.drop_constraint('orders_ibfk_2', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'houses', ['house_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_constraint('package_procedure_infos_ibfk_2', 'package_procedure_infos', type_='foreignkey')
    op.drop_constraint('package_procedure_infos_ibfk_4', 'package_procedure_infos', type_='foreignkey')
    op.drop_constraint('package_procedure_infos_ibfk_3', 'package_procedure_infos', type_='foreignkey')
    op.drop_constraint('package_procedure_infos_ibfk_5', 'package_procedure_infos', type_='foreignkey')
    op.create_foreign_key(None, 'package_procedure_infos', 'company_departments', ['collect_departmentid'], ['id'])
    op.create_foreign_key(None, 'package_procedure_infos', 'users', ['approval_user_id'], ['id'])
    op.create_foreign_key(None, 'package_procedure_infos', 'users', ['collect_user_id'], ['id'])
    op.create_foreign_key(None, 'package_procedure_infos', 'logistics_company_lists', ['logistics_company_id'], ['id'])
    op.add_column('procedure_states', sa.Column('procedure_state_approval_datetime', sa.DateTime(), nullable=True))
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'company_departments', ['departmentid'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'roles', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('users_ibfk_2', 'users', 'company_departments', ['departmentid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_column('procedure_states', 'procedure_state_approval_datetime')
    op.drop_constraint(None, 'package_procedure_infos', type_='foreignkey')
    op.drop_constraint(None, 'package_procedure_infos', type_='foreignkey')
    op.drop_constraint(None, 'package_procedure_infos', type_='foreignkey')
    op.drop_constraint(None, 'package_procedure_infos', type_='foreignkey')
    op.create_foreign_key('package_procedure_infos_ibfk_5', 'package_procedure_infos', 'logistics_company_lists', ['logistics_company_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('package_procedure_infos_ibfk_3', 'package_procedure_infos', 'users', ['collect_user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('package_procedure_infos_ibfk_4', 'package_procedure_infos', 'users', ['approval_user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('package_procedure_infos_ibfk_2', 'package_procedure_infos', 'company_departments', ['collect_departmentid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_ibfk_2', 'orders', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('orders_ibfk_1', 'orders', 'houses', ['house_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint(None, 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint(None, 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint(None, 'car_procedure_infos', type_='foreignkey')
    op.create_foreign_key('car_procedure_infos_ibfk_4', 'car_procedure_infos', 'company_departments', ['departmentid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('car_procedure_infos_ibfk_3', 'car_procedure_infos', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('car_procedure_infos_ibfk_1', 'car_procedure_infos', 'car_lists', ['car_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('car_procedure_infos_ibfk_2', 'car_procedure_infos', 'procedure_lists', ['procedure_list_id'], ['procedure_list_id'], onupdate='RESTRICT', ondelete='RESTRICT')
    # ### end Alembic commands ###
