"""empty message

Revision ID: 9cacd82d9eb6
Revises: 177f21185099
Create Date: 2020-06-12 21:28:57.444551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cacd82d9eb6'
down_revision = '177f21185099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_procedure_infos', sa.Column('departmentid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'car_procedure_infos', 'company_departments', ['departmentid'], ['id'])
    op.add_column('package_procedure_infos', sa.Column('approval_departmentid', sa.Integer(), nullable=True))
    op.add_column('package_procedure_infos', sa.Column('collect_departmentid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'package_procedure_infos', 'company_departments', ['approval_departmentid'], ['id'])
    op.create_foreign_key(None, 'package_procedure_infos', 'company_departments', ['collect_departmentid'], ['id'])
    op.add_column('procedure_lists', sa.Column('procedure_list_departmentid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'procedure_lists', 'company_departments', ['procedure_list_departmentid'], ['id'])
    op.add_column('users', sa.Column('departmentid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'company_departments', ['departmentid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'departmentid')
    op.drop_constraint(None, 'procedure_lists', type_='foreignkey')
    op.drop_column('procedure_lists', 'procedure_list_departmentid')
    op.drop_constraint(None, 'package_procedure_infos', type_='foreignkey')
    op.drop_constraint(None, 'package_procedure_infos', type_='foreignkey')
    op.drop_column('package_procedure_infos', 'collect_departmentid')
    op.drop_column('package_procedure_infos', 'approval_departmentid')
    op.drop_constraint(None, 'car_procedure_infos', type_='foreignkey')
    op.drop_column('car_procedure_infos', 'departmentid')
    # ### end Alembic commands ###
