"""empty message

Revision ID: 9efe8d327e5e
Revises: a08d33581ee4
Create Date: 2020-06-21 16:08:32.252268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9efe8d327e5e'
down_revision = 'a08d33581ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('package_procedure_infos_ibfk_1', 'package_procedure_infos', type_='foreignkey')
    op.drop_column('package_procedure_infos', 'approval_departmentid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_procedure_infos', sa.Column('approval_departmentid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('package_procedure_infos_ibfk_1', 'package_procedure_infos', 'company_departments', ['approval_departmentid'], ['id'])
    # ### end Alembic commands ###
