"""empty message

Revision ID: a08d33581ee4
Revises: d2c564bf8854
Create Date: 2020-06-21 15:16:52.877364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a08d33581ee4'
down_revision = 'd2c564bf8854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistics_company_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=25), nullable=True),
    sa.Column('company_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name')
    )
    op.add_column('package_procedure_infos', sa.Column('logistics_company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'package_procedure_infos', 'logistics_company_lists', ['logistics_company_id'], ['id'])
    op.drop_column('package_procedure_infos', 'logistics_company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_procedure_infos', sa.Column('logistics_company', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'package_procedure_infos', type_='foreignkey')
    op.drop_column('package_procedure_infos', 'logistics_company_id')
    op.drop_table('logistics_company_lists')
    # ### end Alembic commands ###
