"""empty message

Revision ID: a173b060cd0a
Revises: 9cacd82d9eb6
Create Date: 2020-06-12 21:41:32.381792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a173b060cd0a'
down_revision = '9cacd82d9eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_departments', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_departments', 'status')
    # ### end Alembic commands ###
