"""empty message

Revision ID: c91b579c730a
Revises: d225b599c4e4
Create Date: 2020-04-08 20:03:54.709922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91b579c730a'
down_revision = 'd225b599c4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('company', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company')
    op.drop_table('company_departments')
    # ### end Alembic commands ###
