"""empty message

Revision ID: d074a21d483d
Revises: 86688bb4055d
Create Date: 2020-06-25 15:12:20.918328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd074a21d483d'
down_revision = '86688bb4055d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedure_approvals', sa.Column('procedure_approval_company', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procedure_approvals', 'procedure_approval_company')
    # ### end Alembic commands ###
