"""empty message

Revision ID: d225b599c4e4
Revises: 71a3eaddf176
Create Date: 2020-04-06 19:40:51.381630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd225b599c4e4'
down_revision = '71a3eaddf176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_procedure_infos', sa.Column('confirm_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package_procedure_infos', 'confirm_time')
    # ### end Alembic commands ###
