"""empty message

Revision ID: d23cc053398e
Revises: fed5d8b57f19
Create Date: 2020-04-05 22:07:58.633680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23cc053398e'
down_revision = 'fed5d8b57f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_procedure_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedure_list_id', sa.Integer(), nullable=True),
    sa.Column('procedure_name', sa.String(length=15), nullable=True),
    sa.Column('logistics_company', sa.String(length=15), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('destination_company', sa.String(length=15), nullable=True),
    sa.Column('package_name', sa.String(length=15), nullable=True),
    sa.Column('payment_method', sa.String(length=15), nullable=True),
    sa.Column('person', sa.String(length=15), nullable=True),
    sa.Column('department', sa.String(length=15), nullable=True),
    sa.Column('approval_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package_procedure_infos')
    # ### end Alembic commands ###
