"""empty message

Revision ID: d2c564bf8854
Revises: 30c7c6ca2836
Create Date: 2020-06-20 21:46:41.040739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c564bf8854'
down_revision = '30c7c6ca2836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_procedure_infos', sa.Column('current_line_node_id', sa.Integer(), nullable=True))
    op.add_column('package_procedure_infos', sa.Column('procedure_list_flowmodal', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package_procedure_infos', 'procedure_list_flowmodal')
    op.drop_column('package_procedure_infos', 'current_line_node_id')
    # ### end Alembic commands ###
