"""empty message

Revision ID: f20c162ee0af
Revises: e1dfdb701190
Create Date: 2020-05-08 18:39:26.742922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f20c162ee0af'
down_revision = 'e1dfdb701190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedure_approval', sa.Column('current_line_node_id', sa.Integer(), nullable=True))
    op.drop_column('procedure_approval', 'node_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedure_approval', sa.Column('node_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('procedure_approval', 'current_line_node_id')
    # ### end Alembic commands ###
