"""empty message

Revision ID: f584d76ac209
Revises: 292864d04ac3
Create Date: 2020-06-20 21:12:04.621488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f584d76ac209'
down_revision = '292864d04ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package_procedure_infos', 'collect_department')
    op.drop_column('package_procedure_infos', 'approval_department')
    op.drop_column('package_procedure_infos', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_procedure_infos', sa.Column('status', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('package_procedure_infos', sa.Column('approval_department', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('package_procedure_infos', sa.Column('collect_department', mysql.VARCHAR(length=15), nullable=True))
    # ### end Alembic commands ###
