"""empty message

Revision ID: fed5d8b57f19
Revises: 
Create Date: 2020-03-31 10:37:00.362176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed5d8b57f19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_procedure_infos_ibfk_5', 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint('car_procedure_infos_ibfk_4', 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint('car_procedure_infos_ibfk_3', 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint('car_procedure_infos_ibfk_6', 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint('car_procedure_infos_ibfk_1', 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint('car_procedure_infos_ibfk_2', 'car_procedure_infos', type_='foreignkey')
    op.create_foreign_key(None, 'car_procedure_infos', 'users', ['first_approval'], ['id'])
    op.create_foreign_key(None, 'car_procedure_infos', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'car_procedure_infos', 'car_lists', ['car_id'], ['id'])
    op.create_foreign_key(None, 'car_procedure_infos', 'procedure_lists', ['procedure_list_id'], ['id'])
    op.create_foreign_key(None, 'car_procedure_infos', 'users', ['second_approval'], ['id'])
    op.create_foreign_key(None, 'car_procedure_infos', 'users', ['confirmer'], ['id'])
    op.add_column('users', sa.Column('status', sa.String(length=10), nullable=True))
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'roles', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_column('users', 'status')
    op.drop_constraint(None, 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint(None, 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint(None, 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint(None, 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint(None, 'car_procedure_infos', type_='foreignkey')
    op.drop_constraint(None, 'car_procedure_infos', type_='foreignkey')
    op.create_foreign_key('car_procedure_infos_ibfk_2', 'car_procedure_infos', 'users', ['confirmer'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('car_procedure_infos_ibfk_1', 'car_procedure_infos', 'car_lists', ['car_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('car_procedure_infos_ibfk_6', 'car_procedure_infos', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('car_procedure_infos_ibfk_3', 'car_procedure_infos', 'users', ['first_approval'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('car_procedure_infos_ibfk_4', 'car_procedure_infos', 'procedure_lists', ['procedure_list_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('car_procedure_infos_ibfk_5', 'car_procedure_infos', 'users', ['second_approval'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    # ### end Alembic commands ###
